### ISSUE TITLE
Should newline "\n" be a permissible segment separator?

### ISSUE THREAD

**Issue by sl33nyc** [irobayna/stupidedi#106]
I'm pretty new to the stupid world of EDI, but all the examples that I've seen appear to allow a simple newline as a segment separator.  However, [these lines](https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/writer/default.rb#L43-L44) appear to prevent that.

**Comment by irobayna** [comment]
@sl33nyc I have never seen a newline as a segment separator.  I do not know if **ANSI X12 EDI** allows this or not.  

Unless you have a hard requirement, I would probably just use 'regular' segment separators:

```
:segment    => "~\n",
:element    => "*",
:component  => ":",
:repetition => "^"
```

**Comment by sl33nyc** [comment]
I'm not sure I can find anything definitive, but the MSDN has an [opinion](https://msdn.microsoft.com/en-us/library/bb259967(v=bts.20).aspx#Anchor_2) which appears to allow any ASCII character as a segment terminator.  However, it also says that the terminator is not validated against the X12 character set, which does not appear to include whitespace.

Some additional Google results include:
* Newline: https://blogs.sap.com/2014/04/05/separators-in-ansi-x12-edi-message/
* Carriage Return: http://www.iconnect-corp.com/specs/vendors/staples/Staples%20EDI%20Guide%2006-2010.pdf (page 14)

IMHO, it'd be better as a warning instead of an exception.  Otherwise, it'd be great if some setting could disable the separator validation.

**Comment by alexkyllo** [comment]
I did EDI for a few years and I definitely saw \n (and \r\n) used as the segment terminator more than once. But I also never saw a trading partner file that actually passed standards validation, so that doesn't necessarily mean it's valid.

**Comment by kputnam** [comment]
Yeah, my experience matches @alexkyllo in that the trading partner had more power in the relationship. They would send whatever they wanted (including invalid files) and their requirements on files being sent to them weren't negotiable.

Even though special characters might be a gray area in the standard, it probably would not be helpful to prevent users from generating or parsing files that used them as delimiters.

I would welcome a PR to relax the `.blank?` test, but it should include some tests that demonstrate files generated with `:segment => "\n"` or `:element => "\n"` can be read back in using the parser. From a quick check, it looks like the parser does fine if the segment delimiter is `"\n"`.

**Comment by ppazos** [comment]
@sl33nyc segment terminator should be tilde "~".

It can be suffixed by: nothing, "\n" or, "\r\n", what is optional is the suffix for human reading. Some implementations might be more relaxed in terms of the X12 standard.

https://www.ibm.com/support/knowledgecenter/en/SS6V3G_5.3.1/com.ibm.help.gswformstutscreen.doc/GSW_EDI_Delimiters.html

https://docs.oracle.com/cd/E19398-01/820-1275/agdbj/index.html

https://support.microsoft.com/en-sg/help/2723596/biztalk-2010-configuring-segment-terminator-for-an-x12-encoded-interch
