### ISSUE TITLE
NoMethodError: undefined method `def_delegators' for Stupidedi::Config::FunctionalGroupConfig:Class

### ISSUE THREAD

**Issue by lkfken** [irobayna/stupidedi#117]
try to follow your given example, and it failed on the 3rd line
```ruby
require 'stupidedi'

config = Stupidedi::Config.hipaa
parser = Stupidedi::Builder::StateMachine.build(config)
```
NoMethodError: undefined method `def_delegators' for Stupidedi::Config::FunctionalGroupConfig:Class
                 method_missing at org/jruby/RubyBasicObject.java:1655
  <class:FunctionalGroupConfig> at C:/jruby-9.1.6.0/lib/ruby/gems/shared/bundler/gems/stupidedi-38960d75bbd2/lib/stupidedi/config/functional_group_config.rb:25
                 <class:Config> at C:/jruby-9.1.6.0/lib/ruby/gems/shared/bundler/gems/stupidedi-38960d75bbd2/lib/stupidedi/config/functional_group_config.rb:22
             <module:Stupidedi> at C:/jruby-9.1.6.0/lib/ruby/gems/shared/bundler/gems/stupidedi-38960d75bbd2/lib/stupidedi/config/functional_group_config.rb:5
                         <main> at C:/jruby-9.1.6.0/lib/ruby/gems/shared/bundler/gems/stupidedi-38960d75bbd2/lib/stupidedi/config/functional_group_config.rb:2
                         (root) at C:/jruby-9.1.6.0/lib/ruby/gems/shared/bundler/gems/stupidedi-38960d75bbd2/lib/stupidedi/config.rb:1
                     initialize at C:/jruby-9.1.6.0/lib/ruby/gems/shared/bundler/gems/stupidedi-38960d75bbd2/lib/stupidedi/config.rb:32
                         <main> at C:/jruby-9.1.6.0/lib/ruby/gems/shared/bundler/gems/stupidedi-38960d75bbd2/lib/stupidedi/config.rb:75

**Comment by lkfken** [comment]
I try to run the same code in Ruby/Linux (not JRuby/Windows) and it's working.

**Comment by kputnam** [comment]
Thanks, I wouldn't have guessed a JRuby issue. Which version of JRuby are you using?

**Comment by lkfken** [comment]
jruby 9.1.6
