### ISSUE TITLE
Unable to read the time field G62

### ISSUE THREAD

**Issue by rdudacz** [irobayna/stupidedi#121]
Hello,

I am facing a problem when I have a segment with a date and time field and when attempting to read it, I get this error message:

```
/Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:154:in `deconstruct': undefined method `value' for "\e[30mTM.value\e[2m\e[37m[ E337: Time]\e[0m\e[0m\e[0m(11:00:ss)":Stupidedi::Versions::FunctionalGroups::FortyTen::ElementTypes::TimeVal::NonEmpty (NoMethodError)
	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:99:in `map'
	from test_stupidedi.rb:42:in `block in el'
	from test_stupidedi.rb:42:in `map'
	from test_stupidedi.rb:42:in `el'
	from test_stupidedi.rb:86:in `block in <main>'
	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:154:in `deconstruct'
	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:129:in `tap'
	from test_stupidedi.rb:86:in `<main>'
```

Here's a sample of the file:
```
ISA*00*          *00*          *ZZ*HELLO       *02*ABCD           *180406*1536*U*00401*000000002*0*T*>~
GS*SM*7086462438*HELLO*20180406*1536*2*X*004010~
ST*204*0002~
B2**TSVL**2022081140*L*PP*L~
B2A*00~
G62*64*20160527*1*1100*LT~
```

Here's the config:
```
config = Stupidedi::Config.contrib
parser = Stupidedi::Builder::StateMachine.build(config)
```

What am I doing wrong and cannot successfully obtain these fields? I checked the documentation and the format of the file (and the segment) seems to be correct.

Thank you in advance.

**Comment by irobayna** [comment]
@rdudacz Are you able to parse the file using ```edi-pp``` ?

**Comment by rdudacz** [comment]
Hi @irobayna, thank you for your reply. When I run the file through `./bin/edi-pp datafile`, I get back a nicely formatted output (here's highlighted the problematic part from the OP):
```
          SegmentVal[G62: Date/Time](
            ID.value[ E432: Date Qualifier](64: Must Respond By),
            DT.value[ E373: Date](2016-05-27),
            ID.value[ E176: Time Qualifier](1: Must Respond By),
            TM.value[ E337: Time](11:00:ss),
            ID.value[ E623: Time Code](LT: Local Time (Preferred Usage - Explain in detail))),
```
If I run the parser through `edi-pp`, how do I fetch single values (like eg. `E337`) from the output (and then work with it further - saving it to databse)?

I think I am doing something wrong when I manually parse (I follow [this example](https://github.com/irobayna/stupidedi#reading-traversing)) the file. 

If in the file is an information about a date - `20160527 `, after manual parsing is the output `2016-05-27`. Same with floating numbers etc. Why is this?

Thank you very much, @irobayna, highly appreciate your help.

**Comment by irobayna** [comment]
@rdudacz Are you parsing the tree?

Here is some code that might help you:

```ruby
config = Stupidedi::Config.contrib
parser = Stupidedi::Builder::StateMachine.build(config)
input  = File.open("your file name here")
parser, result = parser.read(Stupidedi::Reader.build(input))

# Then traverse the tree 'parser'
 parser.first.tap do |isa|

        ## this is how you would get individual elements

        sender_id    = "#{isa.element(6).map(&:node).fetch(0)}"
        receiver_id  = "#{isa.element(8).map(&:node).fetch(0)}"
        current_date = "#{isa.element(9).map(&:node).fetch(0)}"
        current_time = "#{isa.element(10).map(&:node).fetch(0)}"
        isa_ctrl_no  = "#{isa.element(13).map(&:node).fetch(0)}"

        isa.iterate(:GS) do |gs|
          group_ctrl_no = "#{gs.element(6).map(&:node).fetch(0)}"
          create_date = Interchangeable.parse_edi_date("#{gs.element(4).map(&:node).fetch(0)}")

          gs.iterate(:ST) do |st|
           st.find(:BFR).map do |bfr|
             transaction_set_purpose_code = "#{bfr.element(1).map(&:node).fetch(0)}"
```

In regards to the date, you should format it accordingly to your EDI guidelines.  I have a few helper methods that I use on my own code to help with the date / time parsing:  

```Interchangeable.parse_edi_Date()```

```ruby
def self.parse_edi_date(edi_date)

    if edi_date[0] == 'X'
      # XXYYMMDD
      Time.strptime("#{edi_date}", 'XX%y%m%d')
    else
      # YYYY-MM-DD
      Time.strptime("#{edi_date}", '%Y-%m-%d')
    end
  end
```

**Comment by rdudacz** [comment]
@irobayna thank you very much!

I am parsing a 204 file in this format:
```
ISA*00*          *00*          *ZZ*XXXX       *02*TSVL           *180406*1536*U*00401*000000002*0*T*>~
GS*SM*7086462438*HAHA*20180406*1536*2*X*004010~
ST*204*0002~
B2**HAHA**41225125125*L*PP*L~
B2A*00~
G62*64*20160527*1*1300*LT~
N1*SH*some text*77*556622~
N3*PO Box 123456~
N4*Los Angeles*CA*98765-1234*CA~
G61*SH*abc*TE*note~
... and so on, the file has about ~35 segments...
```

I've been following your example above and parsed the data like this:
```
   isa.iterate(:GS) do |gs|
    	puts 'GS'
   	puts "#{gs.element(8).map(&:node).fetch(0)}"
        puts "group_ctrl_no: #{group_ctrl_no}"
	puts '-'

        gs.iterate(:ST) do |st|
        	puts 'ST'
	   		puts "#{st.element(1).map(&:node).fetch(0)}"
	   		puts "#{st.element(2).map(&:node).fetch(0)}"
	  		puts '-'

		  	st.iterate(:B2) do |b2|
		  		puts 'B2'
		   		puts "#{b2.element(1).map(&:node).fetch(0)}"
		   		puts "#{b2.element(2).map(&:node).fetch(0)}"
		   		puts "#{b2.element(3).map(&:node).fetch(0)}"
		   		puts "#{b2.element(4).map(&:node).fetch(0)}"
		   		puts "#{b2.element(5).map(&:node).fetch(0)}"
		   		puts "#{b2.element(6).map(&:node).fetch(0)}"
		   		puts "#{b2.element(7).map(&:node).fetch(0)}"
		   		puts '-'

		  		b2.iterate(:B2A) do |b2a|
                                   ...
```

I've been able to pull out data from all the segments (except one - OID - I'll explain below), but when I ran the script, o beside extracting all the data, the sript also ended up with this error output: **/Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:629:in `__find': GE segment cannot be reached from the current state (Stupidedi::Exceptions::ParseError)**[full output here](https://gist.github.com/rdudacz/1a5f88dd9ef40951dcde41e8c30a2508).

I remember when I was writing the script, I start seeing this error since the segment **B2**, **B2A**, **N4** etc. Despite the fact the script ended up with error, all data got extracted - what's the cause of that?

Also, the one filed I had a problem with was the field **OID**. Here's an example of it: **OID**142311**CA*162*L*5632*E*114.91~**. There are 9 elements. When I tried to output this segment:
```
g61.iterate(:OID) do |oid| # PROBLEM!!! - 9 fields, not only 8
  puts 'OID:'
  puts "#{oid.element(1).map(&:node).fetch(0)}"
  puts "#{oid.element(2).map(&:node).fetch(0)}"
  puts "#{oid.element(3).map(&:node).fetch(0)}"
  puts "#{oid.element(4).map(&:node).fetch(0)}"
  puts "#{oid.element(5).map(&:node).fetch(0)}"
  puts "#{oid.element(6).map(&:node).fetch(0)}" 
  puts "#{oid.element(7).map(&:node).fetch(0)}"
  puts "#{oid.element(8).map(&:node).fetch(0)}"																		   		 
  puts "#{oid.element(9).map(&:node).fetch(0)}"																		   		 
  puts '-'
end
```
I get this error message: **/Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:141:in `block in element': OID segment has only 8 elements (ArgumentError)** 
I checked the documentation from my carrier and there's indeed 9 elements. Does it mean that I have to overwrite some parts of the librabry?

When I remove that 9th element from the script, this error is gone, but the output is only:
```
OID:

4105301900


832

7233

-
```
I checked the printed out numbers for the **OID** element from the script (4105301900, 832 and 7233) and these are not even in the text file. Is needed to somehow modify the **OID** element in the library?

Thakn you very much, @irobayna!

**Comment by irobayna** [comment]
@rdudacz glad to see you are making progress

You should study your EDI specs and be sure how the loops, segments are defined as some are required and others are relative, dependent, optional so as you traverse the tree you have to see what's available.  This sometimes is tricky.  

To know what's available use the following:

```pp b2.successors```

This will print what you can traverse to.

In regards to the ```OID``` segment, it would help to your at your particular EDI implementation guide for this message to see how all the fields are defined.  Potentially yes, you would add a new ```optional``` field so the current messages keep working as well as your new transaction.   You should send me the Field definition and after we agree there is a new field then send a pull request and I will be happy to merge it.

**Comment by rdudacz** [comment]
Thank you @irobayna, the `OID` segment is a problem and I will probably need to modify the relevant part of the library.

**Comment by umar-siddiqui** [comment]
@rdudacz How did you fix this issue?
