### ISSUE TITLE
"Stupidedi::Exceptions::ZipperError - root node has no siblings" when generating a 990 file

### ISSUE THREAD

**Issue by rdudacz** [irobayna/stupidedi#123]
I look at [this](https://github.com/irobayna/stupidedi#generating-writing) example and tried to generate a 990 file. This is the format of the file (from the documentation):
```
ST*990*12345678~ 
B1*SCAC*2016722352*20150111*A~ 
SE*3*12345678~
```

And this is how I tried to generate it from my application:
```
config = Stupidedi::Config.hipaa
b = Stupidedi::Builder::BuilderDsl.build(config)
b.ST "990", "935030002"
b.B1 "SCAC", "2016722790", "20150622", "A"
b.SE "3", "935030002"    
          
b.machine.zipper.tap do |z|
  separators =Stupidedi::Reader::Separators.build :segment    => "~\n",
                                            :element    => "*",
                                            :component  => ":",
                                            :repetition => "^"

   w = Stupidedi::Writer::Default.new(z.root, separators)
   print w.write()
end
```

But this will result into this error:
`Stupidedi::Exceptions::ZipperError - root node has no siblings:`

How do I generate such a file? The  `ISA` segment is not in the documentation, but the error says there's needed a root for the generated file?

**Comment by kputnam** [comment]
You can find examples in the `notes` directory to get you started, but you will need documentation from your trading partner about particular values to be used in the ISA and GS segments.
