### ISSUE TITLE
Help Parsing

### ISSUE THREAD

**Issue by tomrossi7** [irobayna/stupidedi#125]
I'm sorry if this is dumb, but I'm still getting my arms wrapped around the syntax for parsing. I've gotten to the point where I can loop through and access the first element in a loop, but I can't figure out how to access the next element in the loop. So in this example, I'm able to loop through the SVC segments, but can't figure out how to access the DTM or CAS segment that are in the same 2110 loop. Thanks for any help!

```
    parser, result = parser.read(Stupidedi::Reader.build(file))
    parser.first.tap do |isa|
       isa.iterate(:GS) do |gs|
         gs.iterate(:ST) do |st|
            st.iterate(:LX) do |lx|
              lx.iterate(:CLP) do |clp|
                clp.iterate(:SVC) do |svc|
                  ndc = svc.element(1,2).map(&:node)
                end
              end
            end
          end
        end
      end
    end

```

<img width="691" alt="screen shot 2018-05-07 at 5 05 20 pm" src="https://user-images.githubusercontent.com/64581/39726277-90d20238-521c-11e8-867a-73878a6a580f.png">

**Comment by irobayna** [comment]
@tomrossi7 you should only use ```.iterate``` on loops.

In order to see what is reachable from the ```clp``` segment you can call ```.successor```, but to reach other non loop segments you should call ```.find```

See sample:

![image](https://user-images.githubusercontent.com/349175/39726655-c5f78c20-521d-11e8-924b-d311d905c166.png)

**Comment by tomrossi7** [comment]
Sorry, I'm not tracking with that `find` sample. In my case it would seem like I should do a find for the CAS element within the SVC loop. Each CLP has multiple SVC loops, and each SVC loop has an SVC, DTM, and CAS segment.

```
                clp.iterate(:SVC) do |svc|
                  ndc = svc.element(1,2).map(&:node).fetch(0)
                  adjustment = svc.find(:CAS).element(3).map(&:node).fetch(0)
                end

```

**Comment by tomrossi7** [comment]
I was able to figure this out, but I'm not confident I'm doing it the right way:

                clp.iterate(:SVC) do |svc|
                  ndc = svc.element(1,2).map(&:node).fetch(0)
                  svc.find(:CAS).map do |cas|
                    adjustment = element(3).map(&:node).fetch(0)
                  end
                end

**Comment by irobayna** [comment]
This line seems wrong, you are missing ```cas```

```
   adjustment = element(3).map(&:node).fetch(0)
```

```ruby
          clp.iterate(:SVC) do |svc|
              ndc = svc.element(1,2).map(&:node).fetch(0)
              svc.find(:CAS).map do |cas|
                adjustment = cas.element(3).map(&:node).fetch(0)
              end
            end
```

**Comment by tomrossi7** [comment]
Yeah, sorry, my working code is similar to yours. Does everything else look correct? Should I be calling `iterate` for the SVC and `find` for the CAS?

**Comment by kputnam** [comment]
It might help to remember `find` always returns `Either`... either it found something or it didn't (it doesn't return `nil`). It works similarly to an array that has either zero or one elements, in that you can use `#map` to manipulate the element or do nothing if there wasn't an element. Then `#fetch(default)` is like using `Array#fetch(0, default)`.

Another tip is you can add a few lines here an there to print which elements are find-able or not (this depends on the grammar, not on whether those elements actually exist in your file), which should give some confidence you're on the right track:

```ruby
          puts "From CLP:"; pp clp.successors; puts ""
          # you should see SVC here, since you're trying clp.iterate(:SVC) below

          clp.iterate(:SVC) do |svc|
              puts "From SVC:"; pp svc.successors; puts ""
                # you should see CAS here, since you're trying svc.find(:CAS) below
                # and also see SVC here, since you're implicitly doing svc.find(:SVC)
                # by using clp.iterate(:CLP) above

              ndc = svc.element(1,2).map(&:node).fetch(0)
              svc.find(:CAS).map do |cas|
                adjustment = cas.element(3).map(&:node).fetch(0)
              end
            end
```

**Comment by kputnam** [comment]
Oh, and also `#element` on a segment returns an Either too, since either that element was present or it wasn't (it doesn't return `nil`). That's why you have `cas.element(3).map(&:node).fetch(0)` -- it's similar code as if you had started with `cas = [<item>]` or `cas = []`.

**Comment by tomrossi7** [comment]
Thanks guys!
