### ISSUE TITLE
"can't modify frozen String" while generating 834 output

### ISSUE THREAD

**Issue by lkfken** [irobayna/stupidedi#127]
Hi,

I found errors when generating 834 output.

All these errors are caused by the "<<" operator.
 
For examples,
string_val.rb, Line# 265.
time_val.rb, Line# 229
element_defs.rb, Line# 101
fixnum_val.rb, Line# 242
date_val.rb, Line# 284

Since you put '# frozen_string_literal: true' on these files, then I think you should not use the "<<" operator; instead, they should be changed to "+"

Thank you.

**Comment by irobayna** [comment]
@lkfken could you try generating 834 again?
