### ISSUE TITLE
Not able to find segments after GS segment

### ISSUE THREAD

**Issue by Gauravbtc** [irobayna/stupidedi#128]
Below are the my file 

ISA*00*          *00*          *ZZ*AMAZON         *11*JNS            *180613*0518*U*00400*000000003*0*T*>~
GS*PO*AMAZON*JNS*20180613*0518*3*X*004010~
ST*850*0001~
BEG*00*NE*TBYYXXVN**20180613~REF*CR*JNSBE~
DTM*064*20180613~
DTM*063*20180620~
N1*ST**92*RNO1~
PO1*1*100*EA*0.75*PE*UP*794437195018~
PO1*2*200*EA*1.6*PE*UP*672555112301~
CTT*2*300~SE*10*0001~
GE*1*3~
IEA*1*000000003~

    require "stupidedi"
    config = Stupidedi::Config.hipaa
    parser = Stupidedi::Builder::StateMachine.build(config)
    filepath =  "nameoffile"
    input  = File.open(filepath, :encoding => "ISO-8859-1")     
    parser, result = parser.read(Stupidedi::Reader.build(input))

when i tried to read the file like below way i successfully read GS segment

parser.first.parser.first.flatmap{|m| m.find(:GS) }
it get below output 

Either.success(
  StateMachine[1](
    SegmentVal[GS: Functional Group Header](
      ID.value[ E479: Functional Identifier Code](PO: Purchase Order (850)),
      AN.value[ E142: Application's Sender Code](AMAZON),
      AN.value[ E124: Application Receiver's Code](JNS),
      DT.value[ E373: Date](2018-06-13),
      TM.value[ E337: Time](05:18:ss),
      Nn.value[  E28: Group Control Number](3),
      ID.value[ E455: Responsible Agency Code](X: Accredited Standards Committee X12),
      AN.value[ E480: Version / Release / Identifier Code](004010))))

but when i try to get ST segment data using below way it will raised an error
parser.first..flatmap{|m| m.find(:ST) }
error: 
Stupidedi::Exceptions::ParseError: ST segment cannot be reached from the current state 

can you help me short out this issue thanks in advances

**Comment by kputnam** [comment]
Hi @Gauravbtc. Take a look at doc/Navigating.md (see [rubydoc.info](https://www.rubydoc.info/github/irobayna/stupidedi/file/doc/Navigating.md) where the images are rendered).

When you write `parser.first`, the cursor is placed on the `ISA` segment. From there, you can go to `GS` but not `ST`. You can travel from `GS` to `ST` though. Think of it this way: an `ISA` has many `GS` children, and each `GS` has many `ST` children. So it's unclear and possibly dangerous to ask for an `ST` unless you're positioned already on a `GS` segment.
