### ISSUE TITLE
Trying to define a required segment, get missing segment error for that segment

### ISSUE THREAD

**Issue by timothyfstephens** [irobayna/stupidedi#136]
I'm trying to build a Purchase Order document (PO850) using 4010, and getting this error: 
```
Stupidedi::Exceptions::ParseError: required segment SE is missing from table Table 3 - Summary
```

Code to reproduce:
```
builder = Stupidedi::Builder::BuilderDsl.build(Stupidedi::Config.contrib)
builder.ISA *("00**00**01*NEGO*01*DERMA*180918*1705*U*00401*21403983*0*T*>".split('*'))
builder.GS *("PO*NEGO*DERMA*20000121*1853*111*X*004010".split('*'))
builder.ST *("850*3473".split('*'))
builder.BEG *("00*SA*118997**20000121".split('*'))
builder.DTM *("001*20000131".split('*'))
builder.DTM *("010*20000124".split('*'))
builder.N1 *("BY**92*900".split('*'))
builder.PO1 *("1*1*EA*35**UP*086702084289".split('*'))
builder.CTT *("1".split('*'))
builder.SE *("8*3473".split('*'))       # Error occurs here
builder.GE *("1*111".split('*'))
builder.IEA *("1*000000111".split('*'))
```

**Comment by irobayna** [comment]
@timothyfstephens I believe the issue has to do with the data you are passing to your segments.  What I think it's happening is that the library cannot reach the SE segment.  

Perhaps you can google for a small 850 sample and give it a try.   Pretty sure this message works.

BTW, that's an interesting syntax you use.  

HTH

**Comment by kputnam** [comment]
@timothyfstephens, did you ever get this solved? When I look at the summary table [here](https://github.com/irobayna/stupidedi/blob/master/lib/stupidedi/transaction_sets/004010/implementations/PO850.rb#L97), the CTT loop only contains one segment: CTT.

So there could be a bug in stupidedi somehow mishandling a summary table that starts with a loop. But it might be easily worked around by replacing that `CTT` loop with just a `CTT` segment that would be at the same nesting level as `ST`. Unfortunately I don't have any 4010 PO850 fixture files to be sure that changing that wouldn't break the parsing of other files, but perhaps you can test.

**Comment by kputnam** [comment]
FWIW, your example code seems to work without any errors. There were some changes made a while back that corrected some errors in several transaction grammars and I suspect that was the issue. Closing, but feel free to continue the discussion here.
