### ISSUE TITLE
Small refactor question Schema::CodeList::Internal#code_lists

### ISSUE THREAD

**Issue by natec425** [irobayna/stupidedi#184]
Hi!

I was reviewing this code, and I'm curious if a few of these code snippets were equivalent.

https://github.com/irobayna/stupidedi/blob/742ea06da02b49f4151481f3eeb1799fd2a20fa7/lib/stupidedi/schema/code_list.rb#L39-L51

inlining computed `related`:

```ruby
def code_lists(subset = Sets.universal) 
  if subset.finite?
    Sets.build([self]) + @hash.select do |k, v| 
      subset.include?(k) and v.is_a?(Schema::CodeList) 
    end.values
  else 
    Sets.build([self]) 
  end 
end
```

Removing the use of `Sets.universal`:

```ruby
def code_lists(subset = nil) 
  if !subset.nil?
    Sets.build([self]) + @hash.select do |k, v| 
      subset.include?(k) and v.is_a?(Schema::CodeList) 
    end.values
  else 
    Sets.build([self]) 
  end 
end
```

Looking through the codebase, it seems like the default argument of `Sets.universal` is only used when calling `inject` without an `initial` argument.

Does that sound correct?

Thanks so much for your time!

**Comment by kputnam** [comment]
Yes I believe that's correct. Sorry I typed up an answer a while back and must have closed the tab without posting it. But on a quick scan, I don't think `code_lists` is ever used for any purpose within stupidedi itself.

I think the intent was to have a way to compare the result to the appendix found in 5010 healthcare implementation guides. For instance, it would show your transaction doesn't refer to a code list that was listed in the appendix, or it refers to one that it shouldn't. It might've also been to support a documentation auto-generator.

**Comment by kputnam** [comment]
Closing this as I think the question is addressed, but feel free to continue the discussion here if you have further questions!

**Comment by kputnam** [comment]
Closing this as I think the question is addressed, but feel free to continue the discussion here if you have further questions!
