### ISSUE TITLE
Should this be IdentifierVal instead of StringVal?

### ISSUE THREAD

**Issue by natec425** [irobayna/stupidedi#186]
https://github.com/irobayna/stupidedi/blob/742ea06da02b49f4151481f3eeb1799fd2a20fa7/lib/stupidedi/versions/common/element_types/id.rb#L162-L164

It looks like this might be an overlooked copy-paste. Does it look like that to y'all?

**Comment by kputnam** [comment]
Yep that’s wrong! I rarely copy paste but I tend to zen-out when writing repetitive  code. I’ll accept a PR if you make one!
