### ISSUE TITLE
Missing `or`  in Values::RepeatedElementVal#eq

### ISSUE THREAD

**Issue by natec425** [irobayna/stupidedi#190]
https://github.com/irobayna/stupidedi/blob/61f542797626a87e0c0154dade632b4dcf5c36d6/lib/stupidedi/values/repeated_element_val.rb#L88-L92

Hi hi,

Is this method missing an `or` after the `eql?(other)` call?

**Comment by kputnam** [comment]
Yes it's missing. Good catch!
