### ISSUE TITLE
Segment error

### ISSUE THREAD

**Issue by sunilkumarnagoore** [irobayna/stupidedi#211]
Either.failure("segment ST~ does not occur")
when i ran this libraray with other X12 EDI file i am getting the above error.
what is cause for above error

**Comment by kputnam** [comment]
Sorry there's not enough information here. Feel free to reopen and include instructions on how to reproduce the error. Try running the `edi-pp` and `edi-ed` commands on your file to see if they are valid and parsed correctly.

Make sure to read the example code in the [README](https://github.com/irobayna/stupidedi#reading-traversing) or [this document](https://github.com/irobayna/stupidedi/blob/master/doc/Navigating.md) for more detailed explanation of the API.
