### ISSUE TITLE
No way to access LOOP***

### ISSUE THREAD

**Issue by painforever** [irobayna/stupidedi#217]
Hi,

  Basically I want to construct a 837P file using this gem. My question is simple, according to the sample about 'create and writing' a document(comments removed):

`config = Stupidedi::Config.hipaa

  b = Stupidedi::Parser::BuilderDsl.build(config)
  b.ISA "00", "0708", "00", 'SECRET',
        "ZZ", "SUBMITTER ID",
        "ZZ", "RECEIVER ID",
        "990531", "1230", nil, "00501", "123456789", "1", "T", nil
  b.GS "HC", "SENDER ID", "RECEIVER ID", "19990531", "1230", "1", "X", "005010X222A1"
  b.ST "837", "1234", b.default
  b.BHT "0019", "00", "X"*30, "19990531", Time.now.utc, "CH"
  b.NM1 b.default, "1", "PREMIER BILLING SERVICE", nil, nil, nil, nil, "46", "12EEER000TY"
  b.PER "IC", "JERRY THE CLOWN", "TE", "3056660000"

  b.NM1 "40", "2", "REPRICER JONES", nil, nil, nil, nil, "46", "66783JJT"
  b.HL "1", nil, "20", "1"

  b.NM1 "85", "2", "PREMIER BILLING SERVICE", nil, nil, nil, nil, "XX", "123234560"
  b.N3  "1234 SEAWAY ST"
  b.N4  "MIAMI", "FL", "331111234"
  b.REF "EI", "123667894"
  b.PER "IC", b.blank, "TE", "3056661111"

  b.NM1 "87", "2"
  b.N3 "2345 OCEAN BLVD"
  b.N4 "MIAMI", "FL", "33111"

  b.HL "2", "1", "22", "0"
  b.SBR "S", "18", nil, nil, "12", nil, nil, nil, "MB"

  b.NM1 "IL", "1", "BACON", "KEVIN", nil, nil, nil, "MI", "222334444"
  b.N3  "236 N MAIN ST"
  b.N4  "MIAMI", "FL", "33413"
  b.DMG "D8", "19431022", "F"

  b.machine.zipper.tap do |z|
    separators =
        Stupidedi::Reader::Separators.build :segment    => "~\n",
                                            :element    => "*",
                                            :component  => ":",
                                            :repetition => "^"

    w = Stupidedi::Writer::Default.new(z.root, separators)
    content = w.write()
    File.open("x12text.x12", "a+") do |f|
      f.write(content)
      f.close()
    end
  end`

it's working fine but as you know some segments like "NM1" may exist in multiple different LOOPs at the same time like 2000A, which  is about "Billing Provider", or may exist in 2000B, which is "Subscriber". 

So I can I put them into different LOOPs, for example I want to put 
b.NM1 "40", "2", "REPRICER JONES", nil, nil, nil, nil, "46", "66783JJT" to LOOP 2000B,
and put 
b.NM1 "85", "2", "PREMIER BILLING SERVICE", nil, nil, nil, nil, "XX", "123234560" to LOOP 2000A? 

Thank you very much.

**Comment by kputnam** [comment]
I'm not sure I understand the question, but I think you're asking how to generate Loop 2000A and Loop 2000B, given they both begin with an `NM1` segment.

The specification for 837P is used to determine some values in certain elements of `NM1` are unique to either 2000A or 2000B, so using one of those element values will determine which loop you are generating.

In addition, the segments that were generated already are used to narrow the set of possible (valid) segments that can follow. For instance `NM1*85` can only occur in certain places, like after the `ST` segment, but not after an `HL` segment.

Does that answer your question?

**Comment by painforever** [comment]
@kputnam Hi kputnam, Thanks for the answer, it seems answered part of my question. But when I took a look at 837P doc here [https://soapware.screenstepslive.com/s/documentation/m/5138](url), and let's take an example(just an example...),  if you go to see Segment "**Loop 2310E-Ambulance Pick-Up Location**" and "**Loop 2310F-ambulance Drop-Off Location**", you can see that both LOOPs have 3 Segment which are "NM1", "N3" and "N4". 

So for this case , how could I use this gem to produce those 2 LOOPs and put Elements in different LOOPs?
for example, for **Loop 2310E-Ambulance Pick-Up Location** I wanna do NM1, N3, N4 = 1, 2, 3 and for **Loop 2310F-ambulance Drop-Off Location**, let's do NM1, N3, N4 = 4,5,6.  

Thank you again.

**Comment by kputnam** [comment]
That makes sense. Looking at the documentation you linked, on each individual segment you'll see some of the elements have hard-coded values. For instance, at https://soapware.screenstepslive.com/s/documentation/m/5138/l/48352-segment-nm1 which is the start of the 2310E Ambulance Pickup, you'll see the first element `NM101` must have the value `PW`.

The general naming conventions used in the X12 HIPAA specs imply that all the 2310-X loops can be generated in any order (so A,B,C or A,C,B, etc) because they will all start with the same segment (in your case `NM1`). Once the particular loop is determined by the first segment in the loop (eg, you generate an `NM1` with the first element as `PV`), then the other segments in that loop are constrained accordingly. When you want to generate the next 2310-X loop, you can just generate another `NM1` segment.

**Comment by kputnam** [comment]
The other thing that isn't obvious from the docs you linked is the nested structure of loops. For example, all the 2310 loops occur within a 2300 loop, which itself occurs within another parent structure. It might be clearer by reading the [837 standard](https://github.com/irobayna/stupidedi/blob/master/lib/stupidedi/transaction_sets/005010/standards/HC837.rb#L11) which is kind of an overview, then reading the [837P implementation](https://github.com/irobayna/stupidedi/blob/master/lib/stupidedi/transaction_sets/005010/implementations/X222A1-HC837.rb#L1622) which spells out more details.

**Comment by kputnam** [comment]
Closing this issue, but feel free to ask further questions if needed.
