### ISSUE TITLE
how to actually write sub-elements separated by ":" ? 

### ISSUE THREAD

**Issue by painforever** [irobayna/stupidedi#218]
Hi, 
  
  The question is simple, I have a script that want to construct a 837P file which is like below:

`def real_kill
  config = Stupidedi::Config.hipaa
  x12 = Stupidedi::Parser::BuilderDsl.build(config)

  #---------------------  Header ---------------------------
  x12.ISA "00", 'SOAPWAREIN', "00", '1101081957',
        "ZZ", "WNYICC         ",
        "ZZ", "INDEPEND HEALTH",
        "200312", "1437", "^", "00501", "000000011", "0", "T", ":"
  x12.GS "HC", "WNYICC", "INDEPEND HEALTH", "20200301", "1437", "101", "X", "005010X222A1"
  x12.ST "837", "0001", "005010X222A1"
  x12.BHT "0019", "00", "16", "20200206", "1015", "CH"

  #----------------------  LOOP1000A ------------------------
  x12.NM1 "41", "1", "EAGLEFORCE ASSOCIATES", "Yi", nil, nil, nil, "46", "TGJ23"
  x12.PER "IC", "TEST SUBMITTER", "TE", "2028129585"

  #----------------------  LOOP 1000B -------------------------
  x12.NM1 "40", "2", "IHA BUFFALO", nil, nil, nil, nil, "46", "95308"

  #----------------------  LOOP 2000A -------------------------
  x12.HL "1", nil, "20", "1"

  #----------------------  LOOP 2010AA Start ---------------------
  x12.NM1 '85', '1', 'ASSOCIATES', 'EAGLEFORCE', nil, nil, nil, 'XX', '1932582137'
  x12.N3 '13421 WOODLAND PARK RD', 'Suite 600'
  x12.N4 'HERNDON', 'VA', '201710001'
  x12.REF 'EI', '123456789'

  #----------------------  LOOP 2000B ---------------------
  x12.HL '2', '1', '22', '0'
  x12.SBR 'P', '18', '14376-01', nil, nil, nil, nil, nil, 'HM'

  #---------------------- LOOP 2010BA ---------------------
  x12.NM1 'IL', '1', 'RICHARD', 'DANIEL', nil, nil, nil, 'MI', 'ABC35506703'
  x12.N3 '1600 S Joyce St'
  x12.N4 'ARLINGTON', 'VA', '22202'
  x12.DMG 'D8', '19811202', 'F'

  #---------------------- LOOP 2010BB ---------------------
  x12.NM1 'PR', '2', 'BCBSAR', nil, nil, nil, nil, 'PI', '60054'
  x12.N3 '13241 Woodland Park Dr'
  x12.N4 'New York', 'NY', '14304'

  #---------------------- LOOP 2300 -----------------------
  x12.CLM '26463774', '100', nil, nil, '12:B:1', 'Y', 'A', 'Y', 'Y'
  x12.HI 'ABK:A0223'

  #---------------------- LOOP 2310A ----------------------
  x12.NM1 'DN', '1', 'OUTMAN'
  x12.REF 'G2', '1G'

  #---------------------- LOOP 2400 -----------------------
  x12.LX '1'
  x12.SV1 'HC:97010', '100', 'UN', '1.0', nil, nil, '1'
  x12.DTP '472', 'RD8', '20140514-20140604'

  #tails
  x12.SE "27", "0001"
  x12.GE "1", "101"
  x12.IEA "1", "000000011"

  x12.machine.zipper.tap do |z|
    separators =
        Stupidedi::Reader::Separators.build :segment    => "~\n",
                                            :element    => "*",
                                            :component  => ":",
                                            :repetition => "^"
    w = Stupidedi::Writer::Default.new(z.root, separators)
    print w.write()
    File.open('patient.edi', 'a+') do |f|
      f.write w.write
    end
  end

end`

when I run this it give me:

Traceback (most recent call last):
	6: from sy.rb:78:in `<main>'
	5: from sy.rb:50:in `real_kill'
	4: from /Users/yusong/.rvm/gems/ruby-2.5.1/gems/stupidedi-1.4.0/lib/stupidedi/parser/builder_dsl.rb:103:in `method_missing'
	3: from /Users/yusong/.rvm/gems/ruby-2.5.1/gems/stupidedi-1.4.0/lib/stupidedi/parser/builder_dsl.rb:41:in `segment!'
	2: from /Users/yusong/.rvm/gems/ruby-2.5.1/gems/stupidedi-1.4.0/lib/stupidedi/parser/tokenization.rb:96:in `mksegment_tok'
	1: from /Users/yusong/.rvm/gems/ruby-2.5.1/gems/stupidedi-1.4.0/lib/stupidedi/parser/tokenization.rb:96:in `zip'
/Users/yusong/.rvm/gems/ruby-2.5.1/gems/stupidedi-1.4.0/lib/stupidedi/parser/tokenization.rb:110:in `block in mksegment_tok': CLM05 is a non-repeatable composite element (ArgumentError)

I guess it's because this line: 

12.CLM '26463774', '100', nil, nil, '12:B:1', 'Y', 'A', 'Y', 'Y'
 
CLM05 is '12:B:1', so maybe the error "CLM05 is a non-repeatable composite element (ArgumentError)" has something todo with this?  Thanks.

**Comment by kputnam** [comment]
Yes I think so. Instead of writing ` x12.CLM '26463774', '100', nil, nil, '12:B:1', 'Y', 'A', 'Y', 'Y'`, try replace CLM05 with `b.composite('12', 'B', '1')`.

**Comment by kputnam** [comment]
FYI: I don't think 837's have repeatable elements but if you run into another transaction that does, maybe 270/271 does, you can use `b.repeated('A', 'B', ...)` to generate repeating elements. You can also write `b.composite(b.repeated('A', 'B', ...), ...)` if a component is repeatable or `b.repeated(b.composite('A', 'B', ...), ...)` if the entire composite element is repeatable.

**Comment by kputnam** [comment]
If that didn't answer your question, feel free to add another comment and reopen the issue!
