### ISSUE TITLE
Doesn't handle arbitrarily large input files, and never will be able to

### ISSUE THREAD

**Issue by robmathews** [irobayna/stupidedi#237]
Because the parser parses the entire input file completely into memory, instead of streaming it section by section.

So it worked on the 400K test file from my client in reasonable time, but failed on the 176MB actual file, taking 18GB of memory and more than 24 hours before I killed it (ie, never actually finishing)

Otherwise, a very nice library.

**Comment by kputnam** [comment]
Never say never! I have a separate branch that drastically improves resource consumption (memory and CPU) and I’m making further improvements by implementing some parts in C.

The library has been very stable without major bugs for a long time, so adding native code is a big risk. I’m currently taking a break, but the next task is writing a thorough randomized test suite. I hope to resume work this summer.

Sorry there is not a great workaround in the meantime. Others have had success with spotting large files apart into small single ST/SE transactions. That cannot be done efficiently using stupidedi however.

**Comment by robmathews** [comment]
I've looked at your performance improvements in your other branch, but they are not sufficient.  A 10% or even 100% improvement doesn't address the basic problem.

Basically, unless the code ceases to attempt to parse the entire tree, it will never work for files with ~600K records in them.

But, hey, feel free to defy the laws of physics, I'm not stopping you!

**Comment by kputnam** [comment]
Okay Rob, thanks for your feedback!

**Comment by robmathews** [comment]
wow, an actual real time answer. I'm stunned.

**Comment by robmathews** [comment]
And seriously, you can't just close this; your library doesn't work for real life situations like parsing 834 elibilitiy files, so it would be nice if your documentation noted that.
