### ISSUE TITLE
value PR is not allowed in element NM101

### ISSUE THREAD

**Issue by berkman** [irobayna/stupidedi#240]
I'm trying to parse an 837p sample file, with contents:

`ISA*00*1234      *00*A         *ZZ*1234567        *ZZ*11111          *210508*1141*^*00501*000000101*1*P*:~
GS*HC*XXXXXXX*XXXXX*20170617*1741*101*X*005010X222A1~
ST*837*1239*005010X222A1~
BHT*0019*00*010*20170617*1741*CH~
NM1*41*2*BILLING SERVICER*****46*ABC123~
PER*IC*BOB SMITH*TE*4805551212~
NM1*40*2*RECEIVER*****46*44556~
HL*1**20*1~
NM1*85*2*BILLING PROVIDER*****XX*1122334455~
N3*1234 SOME ROAD~
N4*CHICAGO*IL*606739999~
REF*EI*999999999~
HL*2*1*22*0~
SBR*P*18*******12~
NM1*IL*1*BLOGGS*JOE****MI*1234567890~
N3*1 SOME BLVD~
N4*CHICAGO*IL*606129998~
DMG*D8*19570111*M~
NM1*PR*2*PAYER*****PI*12345~
N3*1 PAYER WAY~
N4*ST LOUIS*MO*212441850~
REF*2U*W1014~
CLM*1000A*140***19:B:1*Y*A*Y*Y~
HI*ABK:I10~
LX*1~
SV1*HC:99213*140*UN*1***1~
DTP*472*D8*20151124~
HL*3*1*22*0~
SBR*P*18*******12~
NM1*IL*1*BLOGGS*FRED****MI*9876543201~
N3*1 ANOTHER STR~
N4*CHICAGO*IL*606129998~
DMG*D8*19700601*M~
NM1*PR*2*PAYER*****PI*12345~
N3*1 PAYER WAY~
N4*ST LOUIS*MO*212441850~
REF*2U*W1014~
CLM*1001A*140***19:B:1*Y*A*Y*Y~
HI*ABK:I10~
LX*1~
SV1*HC:99213*140*UN*1***1~
DTP*472*D8*20151124~
SE*41*1239~
GE*1*101~
IEA*1*000000101~`

The file passes validation with edi-ed and I can view the contents with edi-pp

`LoopVal[2010BB PAYER NAME](
              SegmentVal[NM1: Payer Name](
                ID.value[  E98: Entity Identifier Code](PR: Payer),
                ID.value[E1065: Entity Type Qualifier](2: Non-Person Entity),
                AN.value[E1035: Payer Name](PAYER),
                AN.empty[E1036: Name Last],
                AN.empty[E1037: Name Middle],
                AN.empty[E1038: Name Prefix],
                AN.empty[E1039: Name Suffix],
                ID.value[  E66: Identification Code Qualifier](PI: Payor Identification),
                AN.value[  E67: Payer Identification](12345),
                ID.empty[ E706: Entity Relationship Code],
                ID.empty[  E98: Entity Identifier Code],
                AN.empty[E1035: Name Last or Organization Name]),`

I'm trying to access the payer information, but I'm getting an error.  The code I'm using is:

`parser.first
  .flatmap{|m| m.find(:GS) }
  .flatmap{|m| m.find(:ST) }
  .tap do |m|
    el(m.find(:NM1, "PR"), 2){|e| puts "Payer: #{e}" }`

Here is the error:

> **value PR is not allowed in element NM101 (ArgumentError)**

The example in the README shows me accessing the payer through N1 / PR, but all sample files I'm finding have it nested under NM1 / PR.

Any ideas?

**Comment by kputnam** [comment]
Hi Mike, looking at some diagnostic data, from `ST` the parser thinks the next possible segments are `BHT`, `NM1`, `HL`, or one of the envelope start/end segments.

```ruby
parser.first
  .flatmap{|m| m.find(:GS) }
  .flatmap{|m| m.find(:ST) }
  .tap do |m|
    pp m # Show current state of the state machine (should print an ST segment)
    pp m.successors # Show which segments can be reached from ST
    el(m.find(:N1, "PR"), 2){|e| puts "Payer: #{e}" }
    el(m.find(:N1, "PE"), 2){|e| puts "Payee: #{e}" }
  end
```

I didn't expect that, so I double checked the README example and noticed it's for an 835 payment. Your file is an 837 claim, so it has a different structure.

No matter, we can still figure out how to get the data you want. Looking at your file with `edi-pp`, the `NM1*PR` Payer Name is a child of `HL*_*_22` Subscriber Level. You should be able to descend one child at a time from `GS`, to `ST`, to `HL` to `N1`.

```ruby
parser.first
  .flatmap{|m| m.find(:GS) }
  .flatmap{|m| m.find(:ST) }
  .flatmap{|m| m.find(:HL, nil, nil, "22") }
  .tap do |m|
    pp m
    el(m.find(:NM1, "PR"), 3){|e| puts "Payer: #{e}" }
  end
```

**Comment by berkman** [comment]
This was very helpful, thank you! 

Cheers
