### ISSUE TITLE
The 4010 PO850 in contrib doesn't work

### ISSUE THREAD

**Issue by andrewthad** [irobayna/stupidedi#50]
Some of the segments in the PO850 don't have enough elements to match their definitions. This results in an exception about not having the right number of elements. I'd like to fix it by adding some of them to it, but I would need the PDF that originally informed these definitions.

**Comment by outsmartin** [comment]
I'm currently using the 4010 PO850 and manually adding all things that I need.
I'm working from an internal specification though.

Would it make sense to play back these changes?
